import { app, BrowserWindow, ipcMain } from 'electron';
const db = require('./database');
const { simulateGame } = require('./simulateGame');

// Magic constants auto-generated by Forge's Webpack plugin
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling
if (require('electron-squirrel-startup')) {
  app.quit();
}

// ─── Window ───────────────────────────────────────────────────────────────────

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    height: 700,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  mainWindow.webContents.openDevTools();
};

// ─── IPC Handlers ─────────────────────────────────────────────────────────────

// Returns all 32 teams with win/loss record for the given season
ipcMain.handle('get-standings', (_event: any, season: any = 2024) => {
  const teams = db.prepare('SELECT id, city, name, conference, division FROM teams').all();

  return teams.map((team: any) => {
    const wins = db.prepare(`
      SELECT COUNT(*) as count FROM games
      WHERE season = ? AND is_simulated = 1
      AND ((home_team_id = ? AND home_score > away_score)
        OR (away_team_id = ? AND away_score > home_score))
    `).get(season, team.id, team.id).count;

    const losses = db.prepare(`
      SELECT COUNT(*) as count FROM games
      WHERE season = ? AND is_simulated = 1
      AND ((home_team_id = ? AND home_score < away_score)
        OR (away_team_id = ? AND away_score < home_score))
    `).get(season, team.id, team.id).count;

    return { ...team, wins, losses };
  });
});

// Returns all teams sorted by conference, division, and name
ipcMain.handle('get-teams', () => {
  return db.prepare(
    'SELECT * FROM teams ORDER BY conference, division, name'
  ).all();
});

// Returns the full roster for a given team, sorted by overall rating (best first)
ipcMain.handle('get-roster', (_event: any, teamId: number) => {
  return db.prepare(`
    SELECT first_name, last_name, position, overall_rating, age, speed, strength, awareness
    FROM players
    WHERE team_id = ?
    ORDER BY overall_rating DESC
  `).all(teamId);
});

//Returns all games for a given season, including team names and scores
ipcMain.handle('get-schedule', (_event: any, season: number = 2024) => {
  return db.prepare(`
    SELECT
      g.id, g.week, g.home_score, g.away_score,
      ht.city || ' ' || ht.name AS home_team,
      at.city || ' ' || at.name AS away_team
    FROM games g
    JOIN teams ht ON g.home_team_id = ht.id
    JOIN teams at ON g.away_team_id = at.id
    WHERE g.season = ? AND g.is_simulated = 1
    ORDER BY g.week, g.id
  `).all(season);
});

// Returns a dashboard summary: top 5 teams per conference and last week's scores
ipcMain.handle('get-dashboard', (_event: any, season: number = 2024) => {
  const topAFC = db.prepare(`
    SELECT t.city || ' ' || t.name AS team_name,
      SUM(CASE WHEN (g.home_team_id = t.id AND g.home_score > g.away_score)
                 OR (g.away_team_id = t.id AND g.away_score > g.home_score) THEN 1 ELSE 0 END) AS wins,
      SUM(CASE WHEN (g.home_team_id = t.id AND g.home_score < g.away_score)
                 OR (g.away_team_id = t.id AND g.away_score < g.home_score) THEN 1 ELSE 0 END) AS losses
    FROM teams t
    JOIN games g ON (g.home_team_id = t.id OR g.away_team_id = t.id)
    WHERE g.season = ? AND g.is_simulated = 1 AND t.conference = 'AFC'
    GROUP BY t.id ORDER BY wins DESC LIMIT 5
  `).all(season);

  const topNFC = db.prepare(`
    SELECT t.city || ' ' || t.name AS team_name,
      SUM(CASE WHEN (g.home_team_id = t.id AND g.home_score > g.away_score)
                 OR (g.away_team_id = t.id AND g.away_score > g.home_score) THEN 1 ELSE 0 END) AS wins,
      SUM(CASE WHEN (g.home_team_id = t.id AND g.home_score < g.away_score)
                 OR (g.away_team_id = t.id AND g.away_score < g.home_score) THEN 1 ELSE 0 END) AS losses
    FROM teams t
    JOIN games g ON (g.home_team_id = t.id OR g.away_team_id = t.id)
    WHERE g.season = ? AND g.is_simulated = 1 AND t.conference = 'NFC'
    GROUP BY t.id ORDER BY wins DESC LIMIT 5
  `).all(season);

  const recentGames = db.prepare(`
    SELECT g.week, g.home_score, g.away_score,
      ht.city || ' ' || ht.name AS home_team,
      at.city || ' ' || at.name AS away_team
    FROM games g
    JOIN teams ht ON g.home_team_id = ht.id
    JOIN teams at ON g.away_team_id = at.id
    WHERE g.season = ? AND g.is_simulated = 1
    ORDER BY g.week DESC, g.id DESC LIMIT 8
  `).all(season);

  return { topAFC, topNFC, recentGames };
});

// Returns league leaders for a given season, grouped by stat category
ipcMain.handle('get-stats', (_event: any, season: number = 2024) => {
  const passing = db.prepare(`
    SELECT p.first_name || ' ' || p.last_name AS player_name,
           t.city || ' ' || t.name AS team_name,
           SUM(s.pass_yards) AS pass_yards,
           SUM(s.pass_tds) AS pass_tds,
           SUM(s.interceptions) AS interceptions,
           SUM(s.completions) AS completions,
           SUM(s.pass_attempts) AS pass_attempts
    FROM stats s
    JOIN players p ON s.player_id = p.id
    JOIN teams t ON s.team_id = t.id
    JOIN games g ON s.game_id = g.id
    WHERE g.season = ? AND g.is_simulated = 1 AND s.pass_attempts > 0
    GROUP BY p.id ORDER BY pass_yards DESC LIMIT 15
  `).all(season);

  const rushing = db.prepare(`
    SELECT p.first_name || ' ' || p.last_name AS player_name,
           t.city || ' ' || t.name AS team_name,
           SUM(s.rush_yards) AS rush_yards,
           SUM(s.rush_tds) AS rush_tds,
           SUM(s.rush_attempts) AS rush_attempts
    FROM stats s
    JOIN players p ON s.player_id = p.id
    JOIN teams t ON s.team_id = t.id
    JOIN games g ON s.game_id = g.id
    WHERE g.season = ? AND g.is_simulated = 1 AND s.rush_attempts > 0
    GROUP BY p.id ORDER BY rush_yards DESC LIMIT 15
  `).all(season);

  const receiving = db.prepare(`
    SELECT p.first_name || ' ' || p.last_name AS player_name,
           t.city || ' ' || t.name AS team_name,
           SUM(s.rec_yards) AS rec_yards,
           SUM(s.rec_tds) AS rec_tds,
           SUM(s.receptions) AS receptions,
           SUM(s.targets) AS targets
    FROM stats s
    JOIN players p ON s.player_id = p.id
    JOIN teams t ON s.team_id = t.id
    JOIN games g ON s.game_id = g.id
    WHERE g.season = ? AND g.is_simulated = 1 AND s.targets > 0
    GROUP BY p.id ORDER BY rec_yards DESC LIMIT 15
  `).all(season);

  return { passing, rushing, receiving };
});

// Simulate the full playoff bracket and save results to DB
ipcMain.handle('simulate-playoffs', (_event: any, season: number = 2024) => {
  // Clear any existing playoff games for this season
  db.prepare(`DELETE FROM stats WHERE game_id IN (SELECT id FROM games WHERE season = ? AND is_playoff = 1)`).run(season);
  db.prepare(`DELETE FROM games WHERE season = ? AND is_playoff = 1`).run(season);

  // Seed top 7 teams per conference by regular season wins
  const seedTeams = (conf: string) => {
    const teams = db.prepare(`SELECT id, city, name FROM teams WHERE conference = ?`).all(conf);
    return teams.map((t: any) => {
      const wins = db.prepare(`
        SELECT COUNT(*) as count FROM games
        WHERE season = ? AND is_simulated = 1 AND is_playoff = 0
        AND ((home_team_id = ? AND home_score > away_score)
          OR (away_team_id = ? AND away_score > home_score))
      `).get(season, t.id, t.id).count;
      return { ...t, wins };
    }).sort((a: any, b: any) => b.wins - a.wins).slice(0, 7);
  };

  const afcTeams = seedTeams('AFC');
  const nfcTeams = seedTeams('NFC');

  const insertGame = db.prepare(`
    INSERT INTO games (season, week, home_team_id, away_team_id, home_score, away_score, is_playoff, is_simulated)
    VALUES (?, ?, ?, ?, ?, ?, 1, 1)
  `);

  // Simulate one playoff game, save it, return result
  const simGame = (homeTeam: any, awayTeam: any, week: number) => {
    const result = simulateGame(homeTeam.id, awayTeam.id);
    insertGame.run(season, week, homeTeam.id, awayTeam.id, result.homeScore, result.awayScore);
    const winner = result.homeScore > result.awayScore ? homeTeam : awayTeam;
    return { home: homeTeam, away: awayTeam, homeScore: result.homeScore, awayScore: result.awayScore, winner };
  };

  // Wild Card — week 18 (seed 1 gets bye)
  const afcWC = [
    simGame(afcTeams[1], afcTeams[6], 18),
    simGame(afcTeams[2], afcTeams[5], 18),
    simGame(afcTeams[3], afcTeams[4], 18),
  ];
  const nfcWC = [
    simGame(nfcTeams[1], nfcTeams[6], 18),
    simGame(nfcTeams[2], nfcTeams[5], 18),
    simGame(nfcTeams[3], nfcTeams[4], 18),
  ];

  // Divisional — week 19
  const afcDiv = [
    simGame(afcTeams[0], afcWC[2].winner, 19),
    simGame(afcWC[0].winner, afcWC[1].winner, 19),
  ];
  const nfcDiv = [
    simGame(nfcTeams[0], nfcWC[2].winner, 19),
    simGame(nfcWC[0].winner, nfcWC[1].winner, 19),
  ];

  // Conference Championships — week 20
  const afcChamp = simGame(afcDiv[0].winner, afcDiv[1].winner, 20);
  const nfcChamp = simGame(nfcDiv[0].winner, nfcDiv[1].winner, 20);

  // Super Bowl — week 21
  const superBowl = simGame(afcChamp.winner, nfcChamp.winner, 21);

  return {
    afc: { seeds: afcTeams, wildCard: afcWC, divisional: afcDiv, championship: afcChamp },
    nfc: { seeds: nfcTeams, wildCard: nfcWC, divisional: nfcDiv, championship: nfcChamp },
    superBowl,
  };
});

// Fetch existing playoff bracket (if already simulated)
ipcMain.handle('get-playoffs', (_event: any, season: number = 2024) => {
  return db.prepare(`
    SELECT g.week, g.home_score, g.away_score,
           ht.city || ' ' || ht.name AS home_team,
           at.city || ' ' || at.name AS away_team
    FROM games g
    JOIN teams ht ON g.home_team_id = ht.id
    JOIN teams at ON g.away_team_id = at.id
    WHERE g.season = ? AND g.is_playoff = 1
    ORDER BY g.week, g.id
  `).all(season);
});


// ─── App Lifecycle ─────────────────────────────────────────────────────────────

app.on('ready', createWindow);

// Quit when all windows are closed (except on macOS)
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

// Re-create window on dock click if no windows are open (macOS)
app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});