import { app, BrowserWindow } from 'electron';
import { ipcMain } from 'electron';
const db = require('./database');
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 700,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

ipcMain.handle('get-standings', (_event: any, season: any = 2024) => {
const teams = db.prepare('SELECT id, city, name, conference, division FROM teams').all();
return teams.map((team: any) => {
const wins = db.prepare(`
SELECT COUNT(*) as count FROM games
WHERE season = ? AND is_simulated = 1
AND ((home_team_id = ? AND home_score > away_score)
OR (away_team_id = ? AND away_score > home_score))
`).get(season, team.id, team.id).count;
const losses = db.prepare(`
SELECT COUNT(*) as count FROM games
WHERE season = ? AND is_simulated = 1
AND ((home_team_id = ? AND home_score < away_score)
OR (away_team_id = ? AND away_score < home_score))
`).get(season, team.id, team.id).count;
return { ...team, wins, losses };
});
});
// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
