import { app, BrowserWindow, ipcMain } from 'electron';
const db = require('./database');

// Magic constants auto-generated by Forge's Webpack plugin
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling
if (require('electron-squirrel-startup')) {
  app.quit();
}

// ─── Window ───────────────────────────────────────────────────────────────────

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    height: 700,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  mainWindow.webContents.openDevTools();
};

// ─── IPC Handlers ─────────────────────────────────────────────────────────────

// Returns all 32 teams with win/loss record for the given season
ipcMain.handle('get-standings', (_event: any, season: any = 2024) => {
  const teams = db.prepare('SELECT id, city, name, conference, division FROM teams').all();

  return teams.map((team: any) => {
    const wins = db.prepare(`
      SELECT COUNT(*) as count FROM games
      WHERE season = ? AND is_simulated = 1
      AND ((home_team_id = ? AND home_score > away_score)
        OR (away_team_id = ? AND away_score > home_score))
    `).get(season, team.id, team.id).count;

    const losses = db.prepare(`
      SELECT COUNT(*) as count FROM games
      WHERE season = ? AND is_simulated = 1
      AND ((home_team_id = ? AND home_score < away_score)
        OR (away_team_id = ? AND away_score < home_score))
    `).get(season, team.id, team.id).count;

    return { ...team, wins, losses };
  });
});

// Returns all teams sorted by conference, division, and name
ipcMain.handle('get-teams', () => {
  return db.prepare(
    'SELECT * FROM teams ORDER BY conference, division, name'
  ).all();
});

// Returns the full roster for a given team, sorted by overall rating (best first)
ipcMain.handle('get-roster', (_event: any, teamId: number) => {
  return db.prepare(`
    SELECT first_name, last_name, position, overall_rating, age, speed, strength, awareness
    FROM players
    WHERE team_id = ?
    ORDER BY overall_rating DESC
  `).all(teamId);
});

// ─── App Lifecycle ─────────────────────────────────────────────────────────────

app.on('ready', createWindow);

// Quit when all windows are closed (except on macOS)
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

// Re-create window on dock click if no windows are open (macOS)
app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});